"""Memory package for DataMind v4.0"""

from datamind.memory.session import (
    get_dataframe,
    set_dataframe,
    get_schema_cache,
    set_schema_cache,
    get_summary_text,
    set_summary_text,
    get_chat_history,
    add_chat_message,
    get_pre_generated_chart,
    set_pre_generated_chart,
    get_theme,
    set_theme,
    toggle_theme,
    initialize_session_state,
    clear_chat_history,
    clear_pre_generated_charts,
    clear_schema_cache,
    clear_dataframe,
    add_to_dataset_history,
    compute_schema_cache,
    get_dataset_history,
)

from datamind.memory.feedback import (
    add_rating,
    render_rating_widget,
    render_session_summary,
    clear_feedback_data,
    get_user_preferences,
    get_chart_recommendations,
)

__all__ = [
    # Session state accessors
    "get_dataframe",
    "set_dataframe",
    "get_schema_cache",
    "set_schema_cache",
    "get_summary_text",
    "set_summary_text",
    "get_chat_history",
    "add_chat_message",
    "get_pre_generated_chart",
    "set_pre_generated_chart",
    "get_theme",
    "set_theme",
    "toggle_theme",
    "initialize_session_state",
    "clear_chat_history",
    "clear_pre_generated_charts",
    "clear_schema_cache",
    "clear_dataframe",
    "add_to_dataset_history",
    "compute_schema_cache",
    "get_dataset_history",
    # Feedback
    "add_rating",
    "render_rating_widget",
    "render_session_summary",
    "clear_feedback_data",
    "get_user_preferences",
    "get_chart_recommendations",
]